version: '3.8'

services:
  gms-app:
    build: ./
    command: sh -c "./wait-for-postgres.sh db; /gms-app"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    # restart: always
    image: postgres:latest
    volumes:
    - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"
